import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DeviosProvider from "./context/DevioContext";
import Nav from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <DeviosProvider>
        <body className={inter.className}>

          {children}
        </body>
      </DeviosProvider>
    </html>
  );
}
